### ISSUE TITLE
[Suggestion] Why doing virtual time keeping inside getnstimeofday?

### ISSUE THREAD

**Issue by littlepretty** [annonch/emb-vt#3]
I feel this doesn't feel very correct but maybe I am wrong due to lack of background.

So in your `getnstimeofday`, it is returning virtual time:
https://github.com/annonch/emb-vt/blob/1991cb5a4e597918912a3f078b2f3b423e8d1ccf/kernel/bananaVT/kernel/time/timekeeping.c#L403

but in freeze/unfreeze you are using virtual time again because you are calling getnstimeofday,
https://github.com/annonch/emb-vt/blob/1991cb5a4e597918912a3f078b2f3b423e8d1ccf/kernel/bananaVT/kernel/time.c#L234

https://github.com/annonch/emb-vt/blob/1991cb5a4e597918912a3f078b2f3b423e8d1ccf/kernel/bananaVT/kernel/time.c#L261

I think you should use `__getnstimeofday`, a non-vt version of the gettimeofday in both freeze/unfreeze. (but I notice you commented __getnstimeofday on purpose?)

**Comment by annonch** [comment]
What is the PID of the process that handles (un)freeze_write in fs/proc/base.c ?

I expected that the PID of the handler is not the process itself. This may be the cause of my misunderstanding?

https://github.com/annonch/emb-vt/blob/1991cb5a4e597918912a3f078b2f3b423e8d1ccf/kernel/bananaVT/fs/proc/base.c#L1442

**Comment by littlepretty** [comment]
Suprisingly, commit b9e7618186d5d4d09f5e11dc5ab7bbd3ee330560 fix the issue. For posterity, I am trying to add some comments
* no **process** is handling the (un)freeze_write, it is the kernel, but the context switch happened between the process that calls `echo 1 > /proc/pid` and kernel.
* using vt-getnstimeofday in (un)freeze() in `time.c` definitely caused the problem, though not sure how.
